=== joomla-projects/media-manager-improvement/administrator/components/com_menus/presets/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:joomla.org"
	xmlns="urn:joomla.org">
	<xs:element name="menu" type="menuType"/>
	<xs:simpleType name="typeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="component" />
			<xs:enumeration value="container" />
			<xs:enumeration value="heading" />
			<xs:enumeration value="separator" />
			<xs:enumeration value="url" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="elementType">
		<xs:restriction base="xs:string">
			<xs:pattern value="com_(.+)" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="scopeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="default" />
			<xs:enumeration value="edit" />
			<xs:enumeration value="help" />
			<xs:enumeration value="massmail" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="trueFalse">
		<xs:restriction base="xs:string">
			<xs:enumeration value="true" />
			<xs:enumeration value="false"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="browserNavType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="_blank" />
			<xs:enumeration value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="menuType">
		<xs:sequence>
			<xs:element type="menuitemType" name="menuitem" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="menuitemType" mixed="true">
		<xs:sequence>
			<xs:element type="xs:string" name="params" minOccurs="0" maxOccurs="1"/>
			<xs:element type="menuitemType" name="menuitem" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute type="typeType" name="type" use="required"/>
		<xs:attribute type="xs:string" name="title" use="optional"/>
		<xs:attribute type="xs:string" name="link" use="optional"/>
		<xs:attribute type="xs:string" name="class" use="optional"/>
		<xs:attribute type="xs:string" name="icon" use="optional"/>
		<xs:attribute type="elementType" name="element" use="optional"/>
		<xs:attribute type="trueFalse" name="hidden" use="optional" default="false"/>
		<xs:attribute type="xs:string" name="sql_select" use="optional"/>
		<xs:attribute type="xs:string" name="sql_from" use="optional"/>
		<xs:attribute type="xs:string" name="sql_where" use="optional"/>
		<xs:attribute type="xs:string" name="sql_leftjoin" use="optional"/>
		<xs:attribute type="xs:string" name="sql_innerjoin" use="optional"/>
		<xs:attribute type="xs:string" name="sql_group" use="optional"/>
		<xs:attribute type="xs:string" name="sql_order" use="optional"/>
		<xs:attribute type="browserNavType" name="target" use="optional" default=""/>
		<xs:attribute type="scopeType" name="scope" use="optional" default="default"/>
	</xs:complexType>
</xs:schema>

=== joomla-projects/media-manager-improvement/administrator/components/com_menus/presets/modern.xml
<?xml version="1.0"?>
<menu
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:joomla.org"
	xsi:schemaLocation="urn:joomla.org menu.xsd">
	<menuitem
		title="MOD_MENU_SYSTEM"
		type="heading"
		class="class:cog"
		>
		<menuitem
			type="component"
			title="MOD_MENU_CONTROL_PANEL"
			link="index.php"
			element="com_cpanel"
		/>
		<menuitem
			title="MOD_MENU_CONFIGURATION"
			type="component"
			element="com_config"
			link="index.php?option=com_config"
		/>
		<menuitem
			title="MOD_MENU_GLOBAL_CHECKIN"
			type="component"
			element="com_checkin"
			link="index.php?option=com_checkin"
		/>
		<menuitem
			title="MOD_MENU_CLEAR_CACHE"
			type="component"
			element="com_cache"
			link="index.php?option=com_cache"
		/>
		<menuitem
			title="MOD_MENU_PURGE_EXPIRED_CACHE"
			type="component"
			element="com_cache"
			link="index.php?option=com_cache&amp;view=purge"
		/>
		<menuitem
			title="MOD_MENU_SYSTEM_INFORMATION"
			type="component"
			element="com_admin"
			link="index.php?option=com_admin&amp;view=sysinfo"
		/>
	</menuitem>
	<menuitem
		title="MOD_MENU_COM_USERS_USERS"
		type="heading"
		class="class:users"
		>
		<menuitem
			title="MOD_MENU_COM_USERS_USER_MANAGER"
			type="component"
			element="com_users"
			link="index.php?option=com_users&amp;view=users">
		</menuitem>
		<menuitem
			title="MOD_MENU_COM_USERS_GROUPS"
			type="component"
			element="com_users"
			link="index.php?option=com_users&amp;view=groups">
		</menuitem>
		<menuitem
			title="MOD_MENU_COM_USERS_LEVELS"
			type="component"
			element="com_users"
			link="index.php?option=com_users&amp;view=levels">
		</menuitem>
		<menuitem
			type="separator"
		/>
		<menuitem
			title="MOD_MENU_FIELDS"
			type="component"
			element="com_fields"
			link="index.php?option=com_fields&amp;context=com_users.user"
		/>
		<menuitem
			title="MOD_MENU_FIELDS_GROUP"
			type="component"
			element="com_fields"
			link="index.php?option=com_fields&amp;view=groups&amp;context=com_users.user"
		/>
		<menuitem
			type="separator"
		/>
		<menuitem
			title="MOD_MENU_COM_USERS_NOTES"
			type="component"
			element="com_users"
			link="index.php?option=com_users&amp;view=notes">
		</menuitem>
		<menuitem
			title="MOD_MENU_COM_USERS_NOTE_CATEGORIES"
			type="component"
			element="com_categories"
			link="index.php?option=com_categories&amp;view=categories&amp;extension=com_users">
		</menuitem>
		<menuitem
			type="separator"
		/>
		<menuitem
			title="MOD_MENU_MASS_MAIL_USERS"
			type="component"
			element="com_users"
			link="index.php?option=com_users&amp;view=mail"
			scope="massmail"
		/>
	</menuitem>
	<menuitem
		title="MOD_MENU_MENUS"
		type="heading"
		class="class:list"
		>
		<menuitem
			title="MOD_MENU_MENU_MANAGER"
			type="component"
			element="com_menus"
			link="index.php?option=com_menus&amp;view=menus">
			<menuitem
				title="MOD_MENU_MENU_MANAGER_NEW_MENU"
				type="component"
				element="com_menus"
				link="index.php?option=com_menus&amp;view=menu&amp;layout=edit"
				scope="edit"
			/>
		</menuitem>
		<menuitem
			type="separator"
		/>
		<menuitem
			title="MOD_MENU_MENUS_ALL_ITEMS"
			type="component"
			element="com_menus"
			link="index.php?option=com_menus&amp;view=items&amp;menutype="
		/>
		<!--
		Following is an example of repeatable group based on simple database query.
		This requires sql_* attributes (sql_select and sql_from are required)
		The values can be used like - "{sql:columnName}" in any attribute of repeated elements.
		The repeated elements are place inside this xml node but they will be populated in the same level in the rendered menu
		-->
		<menuitem
			type="separator"
			title="JSITE"
			hidden="false"
			sql_select="a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:mod_languages/', l.image, '.gif') END ELSE 'image:mod_languages/icon-16-language.png' END AS icon"
			sql_from="#__menu_types AS a"
			sql_where="a.client_id = 0"
			sql_leftjoin="#__menu AS m ON m.menutype = a.menutype AND m.home = 1 LEFT JOIN #__languages AS l ON l.lang_code = m.language"
			sql_group="a.id, a.title, a.menutype, m.language, l.image"
			sql_order="a.title ASC">
			<menuitem
				title="{sql:title} "
				type="component"
				element="com_menus"
				link="index.php?option=com_menus&amp;view=items&amp;menutype={sql:menutype}"
				icon="{sql:icon}"
				class="class:menu">
				<menuitem
					title="MOD_MENU_MENU_MANAGER_NEW_MENU_ITEM"
					type="component"
					element="com_menus"
					link="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype={sql:menutype}"
					scope="edit"
				/>
			</menuitem>
		</menuitem>
		<menuitem
			type="separator"
			title="JADMINISTRATOR"
			hidden="false"
			sql_select="title, menutype"
			sql_from="#__menu_types"
			sql_where="client_id = 1"
			sql_order="title ASC">
			<menuitem
				title="{sql:title}"
				type="component"
				element="com_menus"
				link="index.php?option=com_menus&amp;view=items&amp;menutype={sql:menutype}">
				<menuitem
					title="MOD_MENU_MENU_MANAGER_NEW_MENU_ITEM"
					type="component"
					element="com_menus"
					link="index.php?option=com_menus&amp;view=item&amp;layout=edit&amp;menutype={sql:menutype}"
					scope="edit"
				/>
			</menuitem>
		</menuitem>
	</menuitem>
	<menuitem
		title="MOD_MENU_MEDIA_MANAGER"
		type="component"
		element="com_media"
		link="index.php?option=com_media"
		class="class:image"
	/>
	<menuitem
		title="MOD_MENU_COM_CONTENT"
		type="heading"
		class="class:file-text"
		>
		<menuitem
			title="MOD_MENU_COM_CONTENT_ARTICLE_MANAGER"
			type="component"
			element="com_content"
			link="index.php?option=com_content">
		</menuitem>
		<menuitem
			title="MOD_MENU_COM_CONTENT_CATEGORY_MANAGER"
			type="component"
			element="com_categories"
			link="index.php?option=com_categories&amp;extension=com_content">
		</menuitem>
		<menuitem
			title="MOD_MENU_COM_CONTENT_FEATURED"
			type="component"
			element="com_content"
			link="index.php?option=com_content&amp;view=featured"
		/>
		<menuitem
			type="separator"
		/>
		<menuitem
			title="MOD_MENU_FIELDS"
			type="component"
			element="com_fields"
			link="index.php?option=com_fields&amp;context=com_content.article"
		/>
		<menuitem
			title="MOD_MENU_FIELDS_GROUP"
			type="component"
			element="com_fields"
			link="index.php?option=com_fields&amp;view=groups&amp;context=com_content.article"
		/>
	</menuitem>
	<menuitem
		title="MOD_MENU_COMPONENTS"
		type="container"
		class="class:cube"
	/>
	<menuitem
		title="MOD_MENU_EXTENSIONS_EXTENSIONS"
		type="heading"
		class="class:cubes"
		>
		<menuitem
			title="MOD_MENU_EXTENSIONS_EXTENSION_MANAGER"
			type="component"
			element="com_installer"
			link="index.php?option=com_installer">
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_INSTALL"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_UPDATE"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=update"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_MANAGE"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=manage"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_DISCOVER"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=discover"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_DATABASE"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=database"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_WARNINGS"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=warnings"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_LANGUAGES"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=languages"
			/>
			<menuitem
				title="MOD_MENU_INSTALLER_SUBMENU_UPDATESITES"
				type="component"
				element="com_installer"
				link="index.php?option=com_installer&amp;view=updatesites"
			/>
		</menuitem>
		<menuitem
			title="MOD_MENU_EXTENSIONS_MODULE_MANAGER"
			type="component"
			element="com_modules"
			link="index.php?option=com_modules"
		/>
		<menuitem
			title="MOD_MENU_EXTENSIONS_PLUGIN_MANAGER"
			type="component"
			element="com_plugins"
			link="index.php?option=com_plugins"
		/>
		<menuitem
			title="MOD_MENU_EXTENSIONS_TEMPLATE_MANAGER"
			type="component"
			element="com_templates"
			link="index.php?option=com_templates">
			<menuitem
				title="MOD_MENU_COM_TEMPLATES_SUBMENU_STYLES"
				type="component"
				element="com_templates"
				link="index.php?option=com_templates&amp;view=styles"
			/>
			<menuitem
				title="MOD_MENU_COM_TEMPLATES_SUBMENU_TEMPLATES"
				type="component"
				element="com_templates"
				link="index.php?option=com_templates&amp;view=templates"
			/>
		</menuitem>
		<menuitem
			title="MOD_MENU_EXTENSIONS_LANGUAGE_MANAGER"
			type="component"
			element="com_languages"
			link="index.php?option=com_languages">
			<menuitem
				title="MOD_MENU_COM_LANGUAGES_SUBMENU_INSTALLED"
				type="component"
				element="com_languages"
				link="index.php?option=com_languages&amp;view=installed"
			/>
			<menuitem
				title="MOD_MENU_COM_LANGUAGES_SUBMENU_CONTENT"
				type="component"
				element="com_languages"
				link="index.php?option=com_languages&amp;view=languages"
			/>
			<menuitem
				title="MOD_MENU_COM_LANGUAGES_SUBMENU_OVERRIDES"
				type="component"
				element="com_languages"
				link="index.php?option=com_languages&amp;view=overrides"
			/>
		</menuitem>
	</menuitem>
	<menuitem
		title="MOD_MENU_HELP"
		type="heading"
		class="class:info-circle"
		>
		<menuitem
			type="component"
			title="MOD_MENU_HELP_JOOMLA"
			element="com_admin"
			link="index.php?option=com_admin&amp;view=help"
			scope="help"
		/>
		<menuitem
